# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/baffinlite/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/baffinlite/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/baffinlite/proprietary/bin/atrace:system/bin/atrace \
    vendor/samsung/baffinlite/proprietary/bin/atx:system/bin/atx \
    vendor/samsung/baffinlite/proprietary/bin/atxd:system/bin/atxd \
    vendor/samsung/baffinlite/proprietary/bin/BCM4330B1_002.001.003.1025.1257.hcd:system/bin/BCM4330B1_002.001.003.1025.1257.hcd \
    vendor/samsung/baffinlite/proprietary/bin/bkmgrd:system/bin/bkmgrd \
    vendor/samsung/baffinlite/proprietary/bin/glgps:system/bin/glgps \
    vendor/samsung/baffinlite/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/baffinlite/proprietary/bin/gpslogd:system/bin/gpslogd \
    vendor/samsung/baffinlite/proprietary/bin/immvibed:system/bin/immvibed \
    vendor/samsung/baffinlite/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/baffinlite/proprietary/bin/mttlogger:system/bin/mttlogger \
    vendor/samsung/baffinlite/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/baffinlite/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/baffinlite/proprietary/bin/mfgloader:system/bin/mfgloader \
    vendor/samsung/baffinlite/proprietary/bin/usb_portd:system/bin/usb_portd \
    vendor/samsung/baffinlite/proprietary/bin/wlandutservice:system/bin/wlandutservice \
    vendor/samsung/baffinlite/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/samsung/baffinlite/proprietary/etc/usb_portd.conf:system/etc/usb_portd.conf \
    vendor/samsung/baffinlite/proprietary/etc/DiamondVoice_Filter_NB.txt:system/etc/DiamondVoice_Filter_NB.txt \
    vendor/samsung/baffinlite/proprietary/etc/DiamondVoice_Filter_WB.txt:system/etc/DiamondVoice_Filter_WB.txt \
    vendor/samsung/baffinlite/proprietary/etc/DiamondVoice_NB.txt:system/etc/DiamondVoice_NB.txt \
    vendor/samsung/baffinlite/proprietary/etc/DiamondVoice_SF_Filter_NB.txt:system/etc/DiamondVoice_SF_Filter_NB.txt \
    vendor/samsung/baffinlite/proprietary/etc/DiamondVoice_SF_Filter_WB.txt:system/etc/DiamondVoice_SF_Filter_WB.txt \
    vendor/samsung/baffinlite/proprietary/etc/DiamondVoice_WB.txt:system/etc/DiamondVoice_WB.txt \
    vendor/samsung/baffinlite/proprietary/etc/gps/glconfig.xml:system/etc/gps/glconfig.xml \
    vendor/samsung/baffinlite/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/baffinlite/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/samsung/baffinlite/proprietary/etc/Volume.db:system/etc/Volume.db \
    vendor/samsung/baffinlite/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/baffinlite/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/baffinlite/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/baffinlite/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/baffinlite/proprietary/lib/hw/alsa.default.so:system/lib/hw/alsa.default.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/audio.primary.java.so:system/lib/hw/audio.primary.java.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/audio.usb.java.so:system/lib/hw/audio.usb.java.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/gps.java.so:system/lib/hw/gps.java.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/sensors.java.so:system/lib/hw/sensors.java.so \
    vendor/samsung/baffinlite/proprietary/lib/libasound.so:system/lib/libasound.so \
    vendor/samsung/baffinlite/proprietary/lib/libsavscmn.so:system/lib/libsavscmn.so \
    vendor/samsung/baffinlite/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/baffinlite/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v03008.so:system/lib/lib_Samsung_SB_AM_for_ICS_v03008.so \
    vendor/samsung/baffinlite/proprietary/lib/lib_SamsungRec_V03011b.so:system/lib/lib_SamsungRec_V03011b.so \
    vendor/samsung/baffinlite/proprietary/lib/lib_SoundAlive_V01013q.so:system/lib/lib_SoundAlive_V01013q.so \
    vendor/samsung/baffinlite/proprietary/lib/libat.so:system/lib/libat.so \
    vendor/samsung/baffinlite/proprietary/lib/libbralloc.so:system/lib/libbralloc.so \
    vendor/samsung/baffinlite/proprietary/lib/libuip.so:system/lib/libuip.so \
    vendor/samsung/baffinlite/proprietary/lib/libat_stubs.so:system/lib/libat_stubs.so \
    vendor/samsung/baffinlite/proprietary/lib/libatlog.so:system/lib/libatlog.so \
    vendor/samsung/baffinlite/proprietary/lib/libbrcm_ril.so:system/lib/libbrcm_ril.so \
    vendor/samsung/baffinlite/proprietary/lib/libbrcmcutils.so:system/lib/libbrcmcutils.so \
    vendor/samsung/baffinlite/proprietary/lib/libbrcmparser.so:system/lib/libbrcmparser.so \
    vendor/samsung/baffinlite/proprietary/lib/libcapi2.so:system/lib/libcapi2.so \
    vendor/samsung/baffinlite/proprietary/lib/libcontainers.so:system/lib/libcontainers.so \
    vendor/samsung/baffinlite/proprietary/lib/libImmVibeJ.so:system/lib/libImmVibeJ.so \
    vendor/samsung/baffinlite/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/baffinlite/proprietary/lib/librpc.so:system/lib/librpc.so \
    vendor/samsung/baffinlite/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/baffinlite/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/baffinlite/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/baffinlite/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/baffinlite/proprietary/lib/libsmte.so:system/lib/libsmte.so \
    vendor/samsung/baffinlite/proprietary/lib/libsoc.so:system/lib/libsoc.so \
    vendor/samsung/baffinlite/proprietary/lib/libsoundalive.so:system/lib/libsoundalive.so \
    vendor/samsung/baffinlite/proprietary/lib/libSoundAlive_VSP_ver315b_arm.so:system/lib/libSoundAlive_VSP_ver315b_arm.so \
    vendor/samsung/baffinlite/proprietary/lib/libsoundspeed.so:system/lib/libsoundspeed.so \
    vendor/samsung/baffinlite/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/baffinlite/proprietary/lib/libjpeg_turbo.so:system/lib/libjpeg_turbo.so \
    vendor/samsung/baffinlite/proprietary/lib/libaudiopolicy_sec.so:system/lib/libaudiopolicy_sec.so \
    vendor/samsung/baffinlite/proprietary/lib/libsthmb.so:system/lib/libsthmb.so \
    vendor/samsung/baffinlite/proprietary/lib/libuecodec.so:system/lib/libuecodec.so \
    vendor/samsung/baffinlite/proprietary/lib/libusb_config.so:system/lib/libusb_config.so \
    vendor/samsung/baffinlite/proprietary/lib/libVCOS.so:system/lib/libVCOS.so \
    vendor/samsung/baffinlite/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so \
    vendor/samsung/baffinlite/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/baffinlite/proprietary/lib/libVCE_csl.so:system/lib/libVCE_csl.so \
    vendor/samsung/baffinlite/proprietary/lib/libVCE_driver.so:system/lib/libVCE_driver.so \
    vendor/samsung/baffinlite/proprietary/lib/libVCE_imageconv.so:system/lib/libVCE_imageconv.so \
    vendor/samsung/baffinlite/proprietary/lib/libVCE_vtq.so:system/lib/libVCE_vtq.so \
    vendor/samsung/baffinlite/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.vc1.hw.decoder.so:system/lib/libOMX.brcm.video.vc1.hw.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libsavsvc.so:system/lib/libsavsvc.so \
    vendor/samsung/baffinlite/proprietary/lib/libvcdecoder_jni.so:system/lib/libvcdecoder_jni.so \
    vendor/samsung/baffinlite/proprietary/lib/modules/VoiceSolution.ko:system/lib/modules/VoiceSolution.ko \
    vendor/samsung/baffinlite/proprietary/lib/libkeystore_client.so:system/lib/libkeystore_client.so \
    vendor/samsung/baffinlite/proprietary/lib/libnewcapi2.so:system/lib/libnewcapi2.so \
    vendor/samsung/baffinlite/proprietary/lib/libsamsungRecord_ns.so:system/lib/libsamsungRecord_ns.so \
    vendor/samsung/baffinlite/proprietary/lib/lib_DNSe_NRSS_ver225.so:system/lib/lib_DNSe_NRSS_ver225.so \
    vendor/samsung/baffinlite/proprietary/lib/libcontrolcsc.so:system/lib/libcontrolcsc.so \
    vendor/samsung/baffinlite/proprietary/lib/libISP.so:system/lib/libISP.so \
    vendor/samsung/baffinlite/proprietary/lib/libisp2.so:system/lib/libisp2.so \
    vendor/samsung/baffinlite/proprietary/lib/libacdapi_azi.so:system/lib/libacdapi_azi.so \
    vendor/samsung/baffinlite/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/samsung/baffinlite/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/baffinlite/proprietary/lib/egl/libGLES_java.so:system/lib/egl/libGLES_java.so \
    vendor/samsung/baffinlite/proprietary/usr/lib/alsa-lib/libasound_module_pcm_bcmfilter.so:system/usr/lib/alsa-lib/libasound_module_pcm_bcmfilter.so \
    vendor/samsung/baffinlite/proprietary/usr/lib/alsa-lib/libbcm_hp_filter.so:system/usr/lib/alsa-lib/libbcm_hp_filter.so \
    vendor/samsung/baffinlite/proprietary/usr/lib/alsa-lib/libbcm_test_filter.so:system/usr/lib/alsa-lib/libbcm_test_filter.so \
    vendor/samsung/baffinlite/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/samsung/baffinlite/proprietary/lib/hw/camera.java.so:system/lib/hw/camera.java.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/gralloc.java.so:system/lib/hw/gralloc.java.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/hwcomposer.java.so:system/lib/hw/hwcomposer.java.so \
    vendor/samsung/baffinlite/proprietary/vendor/lib/hw/lights.java.so:system/vendor/lib/hw/lights.java.so \
    vendor/samsung/baffinlite/proprietary/vendor/lib/hw/power.java.so:system/vendor/lib/hw/power.java.so \
    vendor/samsung/baffinlite/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/baffinlite/proprietary/lib/drm/libomaplugin.so:system/lib/drm/libomaplugin.so \
    vendor/samsung/baffinlite/proprietary/lib/drm/libplayreadyplugin.so:system/lib/drm/libplayreadyplugin.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/acoustics.default.so:system/lib/hw/acoustics.default.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/audio_policy.java.so:system/lib/hw/audio_policy.java.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/audio.primary.goldfish.so:system/lib/hw/audio.primary.goldfish.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/audio.tms.default.so:system/lib/hw/audio.tms.default.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/bplus.default.so:system/lib/hw/bplus.default.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/camera.goldfish.so:system/lib/hw/camera.goldfish.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/gps.goldfish.so:system/lib/hw/gps.goldfish.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/lights.goldfish.so:system/lib/hw/lights.goldfish.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/power.goldfish.so:system/lib/hw/power.goldfish.so \
    vendor/samsung/baffinlite/proprietary/lib/hw/sensors.goldfish.so:system/lib/hw/sensors.goldfish.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.audio.aac.decoder.so:system/lib/libOMX.brcm.audio.aac.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.audio.aac.encoder.so:system/lib/libOMX.brcm.audio.aac.encoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.audio.amrnb.decoder.so:system/lib/libOMX.brcm.audio.amrnb.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.audio.amrnb.encoder.so:system/lib/libOMX.brcm.audio.amrnb.encoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.audio.amrwb.decoder.so:system/lib/libOMX.brcm.audio.amrwb.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.audio.amrwb.encoder.so:system/lib/libOMX.brcm.audio.amrwb.encoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.audio.mp3.decoder.so:system/lib/libOMX.brcm.audio.mp3.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.audio.mp3.encoder.so:system/lib/libOMX.brcm.audio.mp3.encoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.audio.wma.decoder.so:system/lib/libOMX.brcm.audio.wma.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.dummy.decoder.so:system/lib/libOMX.brcm.video.dummy.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.dummy.encoder.so:system/lib/libOMX.brcm.video.dummy.encoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.h263.decoder.so:system/lib/libOMX.brcm.video.h263.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.h263.encoder.so:system/lib/libOMX.brcm.video.h263.encoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.h264.async.hw.encoder.so:system/lib/libOMX.brcm.video.h264.async.hw.encoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.h264.decoder.so:system/lib/libOMX.brcm.video.h264.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.h264.encoder.so:system/lib/libOMX.brcm.video.h264.encoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.h264.hw.decoder.so:system/lib/libOMX.brcm.video.h264.hw.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.h264.hw.encoder.so:system/lib/libOMX.brcm.video.h264.hw.encoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.mpeg4.decoder.so:system/lib/libOMX.brcm.video.mpeg4.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.mpeg4.encoder.so:system/lib/libOMX.brcm.video.mpeg4.encoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.mpeg4.hw.decoder.so:system/lib/libOMX.brcm.video.mpeg4.hw.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libOMX.brcm.video.vpx.decoder.so:system/lib/libOMX.brcm.video.vpx.decoder.so \
    vendor/samsung/baffinlite/proprietary/lib/libV3D_csc.so:system/lib/libV3D_csc.so \
    vendor/samsung/baffinlite/proprietary/lib/libV3D_driver.so:system/lib/libV3D_driver.so
